services:
  db:
    image: mysql:8.0
    container_name: mysql-8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=seata-server
      - MYSQL_USER=seata
      - MYSQL_PASSWORD=seata
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/mysql/conf:/etc/mysql/conf.d
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/log:/var/log/mysql
    cap_add:
      - SYS_NICE
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - seata-server-net

  seata-server:
    image: seataio/seata-server:2.0.0
    container_name: seata-server-2.0.0
    environment:
      - STORE_MODE=db
      # 以 SEATA_IP 作为 host 注册 seata server
      - SEATA_IP=192.168.101.106
      - SEATA_PORT=8091
    volumes:
      - TZ=Asia/Shanghai
      # https://seata.apache.org/zh-cn/docs/ops/deploy-by-docker-compose/
      - "./seata-server/resources:/seata-server/resources"
    ports:
      - "7091:7091"
      - "8091:8091"
    restart: always
    depends_on:
      - db
    networks:
      - seata-server-net

networks:
  seata-server-net:
    driver: bridge